In [3]:
"""
Iris Flowers Classification Project

Project idea – The iris flowers have different species and you can distinguish them based on the length of 
petals and sepals. Predict the species of a new iris flower.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris

iris = load_iris()

print(iris.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [13]:
"""
4 predictors are used to classify the iris species - sepal length, sepal width, petal length, petal width.
"""
print(iris['data'][0:5,:])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [11]:
"""
0 represents Iris-Setosa, 1 represents Iris-Versicolour, 2 represents Iris-Virginica
"""

print(iris['target'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [29]:
"""
kNN model with k = 1.
"""

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(iris['data'],iris['target'], train_size = 0.33, random_state = 0)

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors = 1, metric = "euclidean")

model.fit(x_train, y_train)

from sklearn.metrics import classification_report

test_predictions = model.predict(x_test)
print(classification_report(y_test, test_predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       0.86      0.94      0.90        33
           2       0.94      0.86      0.90        36

    accuracy                           0.93       101
   macro avg       0.93      0.93      0.93       101
weighted avg       0.93      0.93      0.93       101



In [32]:
print(model.predict([[5.1, 3.5, 1.4, 0.2]]))

[0]


In [33]:
"""
Decision Tree 
"""

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(iris['data'],iris['target'], train_size = 0.33, random_state = 0)

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(x_train, y_train)

from sklearn.metrics import classification_report

test_predictions = model.predict(x_test)
print(classification_report(y_test, test_predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       0.85      1.00      0.92        33
           2       1.00      0.83      0.91        36

    accuracy                           0.94       101
   macro avg       0.95      0.94      0.94       101
weighted avg       0.95      0.94      0.94       101



In [36]:
print(model.predict([[5.1, 3.5, 1.4, 0.2]]))

[0]
